import type { Product } from "@/types/commerce";
import { kamisumiScope } from "./scope";

export const products: Product[] = [
  {
    ...kamisumiScope,
    id: "matcha-kyoto-midori",
    slug: "kyoto-usucha-midori",
    sku: "KMS-MAT-001",
    type: "matcha",
    category: "matcha",
    publicStatus: "low_stock",
    isOriginal: false,
    isArchive: false,
    isNewArrival: true,
    publishedAt: "2026-06-12",
    title: {
      "zh-tw": "京都薄茶抹茶 Midori",
      ja: "京都薄茶抹茶 Midori",
      en: "Kyoto Usucha Matcha Midori",
    },
    shortDescription: {
      "zh-tw": "香氣柔和，適合日常薄茶與牛奶飲品的少量現貨。",
      ja: "香りが穏やかで、日常の薄茶やミルクに合わせやすい少量在庫です。",
      en: "A soft, daily usucha matcha suited to whisked tea and milk drinks.",
    },
    description: {
      "zh-tw": "從京都地區採買的日常型抹茶。正式茶舖名與批次資訊會在公開前確認後補足。",
      ja: "京都エリアで買い付けた日常向けの抹茶です。正式な茶舗名とロット情報は公開前確認後に追記します。",
      en: "A daily matcha sourced in the Kyoto area. Tea house and lot details remain to be confirmed before launch.",
    },
    story: {
      "zh-tw": "適合第一次嘗試日本現地抹茶的人。味道不過度厚重，能作為比較不同茶舖風格的基準。",
      ja: "日本現地の抹茶を初めて試す方に向いた一品です。重すぎず、茶舗ごとの違いを知る基準にもなります。",
      en: "A practical first matcha for comparing Japanese tea profiles without an overly heavy finish.",
    },
    price: { currency: "TWD", amountMinor: 98000 },
    referencePrices: [
      { currency: "JPY", amountMinor: 4600, isReference: true },
      { currency: "USD", amountMinor: 3200, isReference: true },
    ],
    images: [
      {
        src: "/images/placeholders/matcha-canister.svg",
        alt: {
          "zh-tw": "木桌上的抹茶罐與茶筅",
          ja: "木の机に置いた抹茶缶と茶筅",
          en: "Matcha tin and whisk on a wooden table",
        },
        kind: "brand",
      },
      {
        src: "/images/placeholders/matcha-whisked.svg",
        alt: {
          "zh-tw": "已點好的抹茶與茶碗",
          ja: "点てた抹茶と茶碗",
          en: "Whisked matcha in a tea bowl",
        },
        kind: "detail",
      },
    ],
    brandName: {
      "zh-tw": "KAMISUMI Select",
      ja: "KAMISUMI Select",
      en: "KAMISUMI Select",
    },
    region: { "zh-tw": "京都", ja: "京都", en: "Kyoto" },
    shippingNote: {
      "zh-tw": "食品寄送規則與賞味期限需在正式報價時確認。",
      ja: "食品発送ルールと賞味期限は正式見積時に確認します。",
      en: "Food shipping rules and best-before details are confirmed with the quote.",
    },
    estimatedDispatch: {
      "zh-tw": "確認入金後約 3-5 個工作天準備出貨",
      ja: "入金確認後、約3〜5営業日で発送準備",
      en: "Prepared around 3-5 business days after payment confirmation",
    },
    relatedJournalIds: ["journal-matcha-storage"],
    relatedProductIds: ["chasen-standard-bamboo", "first-matcha-set"],
    matchaDetail: {
      weight: "20g",
      bestBefore: {
        "zh-tw": "正式公開前依批次確認",
        ja: "正式掲載前にロットごと確認",
        en: "To be confirmed by lot before launch",
      },
      origin: { "zh-tw": "京都府", ja: "京都府", en: "Kyoto Prefecture" },
      suitableForUsucha: true,
      suitableForKoicha: false,
      bitterness: 2,
      umami: 4,
      aroma: 4,
      sweetness: 3,
      recommendedUse: {
        "zh-tw": ["薄茶", "拿鐵", "冷抹茶"],
        ja: ["薄茶", "ラテ", "冷抹茶"],
        en: ["Usucha", "Latte", "Iced matcha"],
      },
      storage: {
        "zh-tw": "未開封冷暗處，開封後建議密封冷藏並盡早使用。",
        ja: "未開封は冷暗所、開封後は密封して冷蔵し早めに使用してください。",
        en: "Store unopened in a cool dark place; refrigerate sealed after opening.",
      },
      purchaseLimit: {
        "zh-tw": "少量現貨，可能需限制數量。",
        ja: "少量在庫のため数量制限の可能性があります。",
        en: "Quantity may be limited due to small-batch stock.",
      },
      availabilityDifficulty: {
        "zh-tw": "中",
        ja: "中",
        en: "Medium",
      },
      kamisumiComment: {
        "zh-tw": "風味平衡，適合想先建立基準味的人。",
        ja: "味の基準を作りたい方に向く、バランスのよい一缶です。",
        en: "A balanced tin for building a first flavor reference.",
      },
    },
  },
  {
    ...kamisumiScope,
    id: "matcha-uji-hikari",
    slug: "uji-koicha-hikari",
    sku: "KMS-MAT-002",
    type: "matcha",
    category: "matcha",
    publicStatus: "preorder",
    isOriginal: false,
    isArchive: false,
    isNewArrival: false,
    publishedAt: "2026-06-01",
    title: { "zh-tw": "宇治濃茶向抹茶 Hikari", ja: "宇治濃茶向抹茶 Hikari", en: "Uji Koicha Matcha Hikari" },
    shortDescription: {
      "zh-tw": "旨味較深，適合希望比較濃茶感的預購候選。",
      ja: "旨味が深く、濃茶向けの味を比較したい方の予約候補です。",
      en: "A preorder candidate for deeper umami and koicha-style comparison.",
    },
    description: {
      "zh-tw": "此商品以預購方式確認數量。正式茶舖名、價格與賞味期限會在採買前確認。",
      ja: "予約数を確認してから買付する商品です。正式な茶舗名、価格、賞味期限は買付前に確認します。",
      en: "A preorder item. Tea house, price, and best-before details are confirmed before sourcing.",
    },
    story: {
      "zh-tw": "適合已經喝過幾款薄茶，想往更濃厚口感前進的人。",
      ja: "薄茶をいくつか試し、より濃厚な味へ進みたい方に向いています。",
      en: "For drinkers ready to move from light usucha toward a richer profile.",
    },
    price: { currency: "TWD", amountMinor: 148000 },
    referencePrices: [{ currency: "JPY", amountMinor: 6900, isReference: true }],
    images: [
      {
        src: "/images/placeholders/matcha-whisked.svg",
        alt: { "zh-tw": "濃綠色抹茶表面", ja: "濃い緑の抹茶の表面", en: "Deep green matcha surface" },
        kind: "detail",
      },
    ],
    brandName: { "zh-tw": "KAMISUMI Select", ja: "KAMISUMI Select", en: "KAMISUMI Select" },
    region: { "zh-tw": "宇治周辺", ja: "宇治周辺", en: "Uji area" },
    shippingNote: {
      "zh-tw": "出貨預定會依預購數量與採買結果調整。",
      ja: "予約数量と買付結果により発送予定が変わります。",
      en: "Dispatch timing depends on preorder quantity and sourcing result.",
    },
    estimatedDispatch: {
      "zh-tw": "採買完成後個別通知",
      ja: "買付完了後に個別案内",
      en: "Confirmed after sourcing",
    },
    relatedJournalIds: ["journal-sourcing-kyoto"],
    relatedProductIds: ["kyoto-usucha-midori"],
    matchaDetail: {
      weight: "20g",
      origin: { "zh-tw": "京都府", ja: "京都府", en: "Kyoto Prefecture" },
      suitableForUsucha: true,
      suitableForKoicha: true,
      bitterness: 2,
      umami: 5,
      aroma: 5,
      sweetness: 4,
      recommendedUse: {
        "zh-tw": ["濃茶", "特別薄茶"],
        ja: ["濃茶", "特別な薄茶"],
        en: ["Koicha", "Special usucha"],
      },
      storage: {
        "zh-tw": "正式批次確認後補充。",
        ja: "正式ロット確認後に記載します。",
        en: "To be added after lot confirmation.",
      },
      availabilityDifficulty: { "zh-tw": "高", ja: "高", en: "High" },
    },
  },
  {
    ...kamisumiScope,
    id: "ceramic-shigaraki-earth",
    slug: "shigaraki-chawan-earth",
    sku: "KMS-CER-001",
    type: "ceramic",
    category: "ceramics",
    publicStatus: "sourcing_available",
    isOriginal: false,
    isArchive: false,
    isNewArrival: true,
    publishedAt: "2026-06-10",
    title: { "zh-tw": "信樂風手作茶碗 Earth", ja: "信楽風手作り茶碗 Earth", en: "Shigaraki-style Chawan Earth" },
    shortDescription: {
      "zh-tw": "釉色與土感每件不同，可依下次採買詢問。",
      ja: "釉薬と土の表情が一点ごとに異なり、次回買付で相談できます。",
      en: "A handmade-feel bowl with varied clay and glaze expression, available by sourcing request.",
    },
    description: {
      "zh-tw": "陶器類以個體差為魅力。尺寸、釉色與箱有無需依現地確認。",
      ja: "陶器は個体差を魅力として扱います。寸法、釉薬、箱の有無は現地で確認します。",
      en: "Ceramic individuality is part of the appeal. Dimensions, glaze, and box status are checked locally.",
    },
    story: {
      "zh-tw": "適合作為日常點茶碗，也可作為禮物候選。採買時會優先確認高台、釉面與破損風險。",
      ja: "日常の点茶碗にもギフト候補にも向きます。買付時は高台、釉面、破損リスクを確認します。",
      en: "Suitable for daily matcha or gifting. Foot, glaze, and breakage risk are checked during sourcing.",
    },
    price: { currency: "TWD", amountMinor: 168000 },
    referencePrices: [{ currency: "JPY", amountMinor: 7800, isReference: true }],
    images: [
      {
        src: "/images/placeholders/chawan-earth.svg",
        alt: { "zh-tw": "土色手作茶碗", ja: "土色の手作り茶碗", en: "Earth-toned handmade tea bowl" },
        kind: "brand",
      },
    ],
    brandName: { "zh-tw": "KAMISUMI Select", ja: "KAMISUMI Select", en: "KAMISUMI Select" },
    region: { "zh-tw": "關西", ja: "関西", en: "Kansai" },
    shippingNote: {
      "zh-tw": "陶器需依實物尺寸與防破損包裝確認運費。",
      ja: "陶器は実寸と破損防止梱包により送料を確認します。",
      en: "Shipping is quoted after actual size and protective packing are checked.",
    },
    estimatedDispatch: {
      "zh-tw": "採買成功後個別通知",
      ja: "買付成功後に個別案内",
      en: "Confirmed after successful sourcing",
    },
    relatedJournalIds: ["journal-ceramic-care"],
    relatedProductIds: ["mino-yunomi-ash"],
    ceramicDetail: {
      dimensions: "約 12 × 8 cm",
      capacity: "約 450 ml",
      weight: "約 360 g",
      material: { "zh-tw": "陶器", ja: "陶器", en: "Ceramic" },
      glaze: { "zh-tw": "灰釉系", ja: "灰釉系", en: "Ash glaze style" },
      microwaveSafe: false,
      dishwasherSafe: false,
      boxIncluded: false,
      handmadeVariation: true,
      careBeforeUse: {
        "zh-tw": "使用前是否需要預先處理，會依作品確認。",
        ja: "使用前の目止めの要否は作品ごとに確認します。",
        en: "Pre-use sealing needs are checked per piece.",
      },
      breakagePolicyNote: {
        "zh-tw": "破損時的處理規約尚未確定，公開前需由專業人士確認。",
        ja: "破損時対応は正式規約確定前のため、公開前に専門確認予定です。",
        en: "Breakage policy requires expert review before launch.",
      },
    },
  },
  {
    ...kamisumiScope,
    id: "ceramic-mino-yunomi",
    slug: "mino-yunomi-ash",
    sku: "KMS-CER-002",
    type: "ceramic",
    category: "ceramics",
    publicStatus: "in_stock",
    isOriginal: false,
    isArchive: false,
    isNewArrival: false,
    publishedAt: "2026-05-28",
    title: { "zh-tw": "美濃灰釉湯呑 Ash", ja: "美濃灰釉湯呑 Ash", en: "Mino Ash Glaze Yunomi" },
    shortDescription: {
      "zh-tw": "手感溫和的日常湯呑，適合日本茶與日常使用。",
      ja: "手になじむ日常使いの湯呑。日本茶に合わせやすい器です。",
      en: "A gentle everyday yunomi for Japanese tea.",
    },
    description: {
      "zh-tw": "少量現貨。實物紋理與釉色略有差異，出貨前可確認照片。",
      ja: "少量在庫です。実物の表情には個体差があり、発送前に写真確認できます。",
      en: "Small-batch stock. Each piece varies slightly; photos can be confirmed before shipment.",
    },
    story: {
      "zh-tw": "不是華麗的展示品，而是每天會想拿起來的茶杯。",
      ja: "華やかな展示品というより、毎日手に取りたくなる湯呑です。",
      en: "A cup meant for daily reach rather than display alone.",
    },
    price: { currency: "TWD", amountMinor: 76000 },
    referencePrices: [{ currency: "JPY", amountMinor: 3600, isReference: true }],
    images: [
      {
        src: "/images/placeholders/yunomi-ash.svg",
        alt: { "zh-tw": "灰釉湯呑", ja: "灰釉の湯呑", en: "Ash glaze tea cup" },
        kind: "brand",
      },
    ],
    brandName: { "zh-tw": "KAMISUMI Select", ja: "KAMISUMI Select", en: "KAMISUMI Select" },
    region: { "zh-tw": "岐阜", ja: "岐阜", en: "Gifu" },
    shippingNote: {
      "zh-tw": "與其他陶器合併包裝時會重新確認包裝與運費。",
      ja: "他の陶器と同梱する場合は梱包と送料を再確認します。",
      en: "Packing and shipping are rechecked when bundled with other ceramics.",
    },
    estimatedDispatch: {
      "zh-tw": "確認入金後約 3-5 個工作天準備出貨",
      ja: "入金確認後、約3〜5営業日で発送準備",
      en: "Prepared around 3-5 business days after payment confirmation",
    },
    relatedJournalIds: ["journal-ceramic-care"],
    relatedProductIds: ["shigaraki-chawan-earth"],
    ceramicDetail: {
      dimensions: "約 8 × 8.5 cm",
      capacity: "約 240 ml",
      material: { "zh-tw": "陶器", ja: "陶器", en: "Ceramic" },
      glaze: { "zh-tw": "灰釉", ja: "灰釉", en: "Ash glaze" },
      microwaveSafe: false,
      dishwasherSafe: false,
      boxIncluded: false,
      handmadeVariation: true,
      careBeforeUse: {
        "zh-tw": "首次使用前建議以清水清洗並自然乾燥。",
        ja: "初回使用前に水洗いし、自然乾燥させてください。",
        en: "Rinse with water and air dry before first use.",
      },
    },
  },
  {
    ...kamisumiScope,
    id: "chasen-standard",
    slug: "chasen-standard-bamboo",
    sku: "KMS-TOL-001",
    type: "tea_tool",
    category: "tea-tools",
    publicStatus: "awaiting_arrival",
    isOriginal: false,
    isArchive: false,
    isNewArrival: false,
    publishedAt: "2026-05-20",
    title: { "zh-tw": "標準竹茶筅", ja: "標準竹茶筅", en: "Standard Bamboo Chasen" },
    shortDescription: {
      "zh-tw": "日常點茶用的基本茶筅，等待下一批到貨。",
      ja: "日常の点茶に使いやすい基本の茶筅。次回入荷待ちです。",
      en: "A standard bamboo whisk for daily matcha, awaiting arrival.",
    },
    description: {
      "zh-tw": "與抹茶、茶碗一起搭配的基本茶道具。保存與使用後乾燥方式會於 Journal 補充。",
      ja: "抹茶や茶碗と合わせる基本の茶道具です。保管と乾燥方法はJournalでも補足します。",
      en: "A core tea tool paired with matcha and bowls. Care notes are expanded in the journal.",
    },
    story: {
      "zh-tw": "初次組合茶具時，茶筅的品質會直接影響點茶手感。",
      ja: "最初に茶道具を揃えるとき、茶筅の状態は点てやすさに直結します。",
      en: "A whisk's condition strongly affects how easily matcha foams.",
    },
    price: { currency: "TWD", amountMinor: 52000 },
    referencePrices: [{ currency: "JPY", amountMinor: 2400, isReference: true }],
    images: [
      {
        src: "/images/placeholders/chasen-tools.svg",
        alt: { "zh-tw": "竹茶筅與茶杓", ja: "竹茶筅と茶杓", en: "Bamboo whisk and tea scoop" },
        kind: "brand",
      },
    ],
    brandName: { "zh-tw": "KAMISUMI Select", ja: "KAMISUMI Select", en: "KAMISUMI Select" },
    shippingNote: {
      "zh-tw": "可與抹茶合併包裝，運費需依包裝確認。",
      ja: "抹茶との同梱が可能です。送料は梱包確認後に案内します。",
      en: "Can be bundled with matcha; shipping is confirmed after packing.",
    },
    estimatedDispatch: {
      "zh-tw": "到貨後個別通知",
      ja: "入荷後に個別案内",
      en: "Confirmed after arrival",
    },
    relatedJournalIds: ["journal-matcha-storage"],
    relatedProductIds: ["kyoto-usucha-midori"],
  },
  {
    ...kamisumiScope,
    id: "gift-first-matcha",
    slug: "first-matcha-set",
    sku: "KMS-GFT-001",
    type: "gift_set",
    category: "gift-sets",
    publicStatus: "coming_soon",
    isOriginal: true,
    isArchive: false,
    isNewArrival: false,
    publishedAt: "2026-05-14",
    title: { "zh-tw": "First Matcha Set 開發中", ja: "First Matcha Set 開発中", en: "First Matcha Set in Development" },
    shortDescription: {
      "zh-tw": "抹茶、茶筅與茶碗的入門組合。正式內容尚未確定。",
      ja: "抹茶、茶筅、茶碗を合わせた入門セット。正式内容は未確定です。",
      en: "An entry set with matcha, whisk, and bowl. Final contents are not fixed.",
    },
    description: {
      "zh-tw": "KAMISUMI EDITIONS 的開發候選。價格、內容與包裝需在試作後決定。",
      ja: "KAMISUMI EDITIONSの開発候補です。価格、内容、包装は試作後に決定します。",
      en: "A KAMISUMI EDITIONS candidate. Price, contents, and packaging will be decided after prototyping.",
    },
    story: {
      "zh-tw": "希望讓第一次開始點茶的人，不需要在資訊中迷路。",
      ja: "初めて点茶を始める人が、情報の中で迷わないためのセットを目指します。",
      en: "Aiming to make first matcha preparation less confusing.",
    },
    price: { currency: "TWD", amountMinor: 0 },
    referencePrices: [],
    images: [
      {
        src: "/images/placeholders/gift-set.svg",
        alt: { "zh-tw": "抹茶入門禮盒概念", ja: "抹茶入門ギフトのコンセプト", en: "First matcha gift concept" },
        kind: "brand",
      },
    ],
    brandName: { "zh-tw": "KAMISUMI Editions", ja: "KAMISUMI Editions", en: "KAMISUMI Editions" },
    shippingNote: {
      "zh-tw": "正式推出前尚未確定。",
      ja: "正式発売前のため未定です。",
      en: "To be decided before release.",
    },
    estimatedDispatch: {
      "zh-tw": "尚未確定",
      ja: "未定",
      en: "To be confirmed",
    },
    relatedJournalIds: ["journal-making-editions"],
    relatedProductIds: ["kyoto-usucha-midori", "chasen-standard-bamboo"],
  },
  {
    ...kamisumiScope,
    id: "archive-spring-chawan",
    slug: "spring-chawan-archive",
    sku: "KMS-ARC-001",
    type: "ceramic",
    category: "ceramics",
    publicStatus: "archive",
    isOriginal: false,
    isArchive: true,
    isNewArrival: false,
    publishedAt: "2026-04-22",
    title: { "zh-tw": "春色茶碗 Archive", ja: "春色茶碗 Archive", en: "Spring Chawan Archive" },
    shortDescription: {
      "zh-tw": "已售出的參考展示。可作為未來採買諮詢方向。",
      ja: "販売済みの参考掲載です。今後の買付相談の方向性として残します。",
      en: "A sold reference item kept for future sourcing direction.",
    },
    description: {
      "zh-tw": "此商品已不作為現貨販售，保留作為類似商品諮詢的參考。",
      ja: "この商品は在庫販売していません。類似商品の相談参考として掲載しています。",
      en: "This item is not available for stock sale and remains as a sourcing reference.",
    },
    story: {
      "zh-tw": "柔和釉色與小尺寸，適合希望找相似手感茶碗的人。",
      ja: "やわらかい釉薬と小ぶりな寸法で、似た雰囲気の茶碗相談に使えます。",
      en: "Soft glaze and compact size make it useful as a reference for similar bowl requests.",
    },
    price: { currency: "TWD", amountMinor: 0 },
    referencePrices: [],
    images: [
      {
        src: "/images/placeholders/chawan-archive.svg",
        alt: { "zh-tw": "參考展示的春色茶碗", ja: "参考掲載の春色茶碗", en: "Archived spring-colored tea bowl" },
        kind: "brand",
      },
    ],
    brandName: { "zh-tw": "KAMISUMI Archive", ja: "KAMISUMI Archive", en: "KAMISUMI Archive" },
    shippingNote: {
      "zh-tw": "參考展示，無出貨預定。",
      ja: "参考掲載のため発送予定はありません。",
      en: "Archive item; not available for shipping.",
    },
    estimatedDispatch: { "zh-tw": "不適用", ja: "対象外", en: "Not applicable" },
    relatedJournalIds: ["journal-ceramic-care"],
    relatedProductIds: ["shigaraki-chawan-earth"],
    ceramicDetail: {
      dimensions: "約 11 × 7 cm",
      material: { "zh-tw": "陶器", ja: "陶器", en: "Ceramic" },
      glaze: { "zh-tw": "淡色釉", ja: "淡色釉", en: "Pale glaze" },
      handmadeVariation: true,
    },
  },
];
